SET MODE ORACLE;
DROP TABLE IF EXISTS "ADDRESS";
DROP SEQUENCE IF EXISTS USER_ID_SEQUENCE;
CREATE SEQUENCE ADDRESS_ID_SEQUENCE START WITH 1000 INCREMENT BY 1;
CREATE TABLE "ADDRESS"
(
   "ID" BIGINT DEFAULT ADDRESS_ID_SEQUENCE.NEXTVAL PRIMARY KEY,
   "TYPE" INTEGER NOT NULL,
   "LOCALITY" VARCHAR (50),
   "CITY" VARCHAR (50) NOT NULL,
   "ZIP" INTEGER NOT NULL
);
