management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans


loki:
  url: http://loki:3100/loki/api/v1/push


api:
  url:
    address: http://address-service:8085/api/v1/address/