server:
  port: 8085
spring:
  application:
    name: address-service
  jpa:
    open-in-view: false
  main:
    banner-mode: "off"

logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.zalando.logbook: TRACE

management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        greeting:
          call: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  show-actuator: true


logbook:
  include:
    - /api/**
  exclude:
    - /actuator/**
  filter.enabled: true
  format.style: http
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000